language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements/dev.txt
script:
  python manage.py test
before_script:
  - pep8 --exclude=migrations --ignore=E501 ./
  - pyflakes ./
