# Generated by Django 2.0.9 on 2019-01-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20151203_2315'),
        ('inventory', '0003_auto_20160914_1049'),
    ]

    operations = [
    ]
